// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package grpc.smartWarehouse.orderManagement;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customerName = 1;</code>
   */
  java.lang.String getCustomerName();
  /**
   * <code>string customerName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCustomerNameBytes();

  /**
   * <code>string itemID = 2;</code>
   */
  java.lang.String getItemID();
  /**
   * <code>string itemID = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemIDBytes();

  /**
   * <code>int32 orderQuantities = 3;</code>
   */
  int getOrderQuantities();

  /**
   * <code>string orderID = 4;</code>
   */
  java.lang.String getOrderID();
  /**
   * <code>string orderID = 4;</code>
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();

  /**
   * <code>string newStatus = 5;</code>
   */
  java.lang.String getNewStatus();
  /**
   * <code>string newStatus = 5;</code>
   */
  com.google.protobuf.ByteString
      getNewStatusBytes();
}
