// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trackingDelivery.proto

package grpc.smartWarehouse.trackingDelivery;

public interface TrackingReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.TrackingReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deliveryDetail = 1;</code>
   */
  java.lang.String getDeliveryDetail();
  /**
   * <code>string deliveryDetail = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeliveryDetailBytes();

  /**
   * <code>string currentLocation = 2;</code>
   */
  java.lang.String getCurrentLocation();
  /**
   * <code>string currentLocation = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrentLocationBytes();

  /**
   * <code>string estimatedDeliveryDate = 3;</code>
   */
  java.lang.String getEstimatedDeliveryDate();
  /**
   * <code>string estimatedDeliveryDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getEstimatedDeliveryDateBytes();

  /**
   * <code>string success_failureMessage = 4;</code>
   */
  java.lang.String getSuccessFailureMessage();
  /**
   * <code>string success_failureMessage = 4;</code>
   */
  com.google.protobuf.ByteString
      getSuccessFailureMessageBytes();

  /**
   * <code>string orderID = 5;</code>
   */
  java.lang.String getOrderID();
  /**
   * <code>string orderID = 5;</code>
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();
}
