// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trackingDelivery.proto

package grpc.smartWarehouse.trackingDelivery;

public final class TrackingDeliveryServiceImpl {
  private TrackingDeliveryServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_TrackingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_TrackingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_TrackingReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_TrackingReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026trackingDelivery.proto\022\016smartwarehouse" +
      "\"\"\n\017TrackingRequest\022\017\n\007orderID\030\001 \001(\t\"_\n\r" +
      "TrackingReply\022\026\n\016deliveryDetail\030\001 \001(\t\022\027\n" +
      "\017currentLocation\030\002 \001(\t\022\035\n\025estimatedDeliv" +
      "eryDate\030\003 \001(\t2m\n\022TrackingManagement\022W\n\023C" +
      "heckShippingDetail\022\037.smartwarehouse.Trac" +
      "kingRequest\032\035.smartwarehouse.TrackingRep" +
      "ly\"\000BE\n$grpc.smartWarehouse.trackingDeli" +
      "veryB\033TrackingDeliveryServiceImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartwarehouse_TrackingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartwarehouse_TrackingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_TrackingRequest_descriptor,
        new java.lang.String[] { "OrderID", });
    internal_static_smartwarehouse_TrackingReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartwarehouse_TrackingReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_TrackingReply_descriptor,
        new java.lang.String[] { "DeliveryDetail", "CurrentLocation", "EstimatedDeliveryDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
