// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trackingDelivery.proto

package grpc.smartWarehouse.trackingDelivery;

public interface TrackingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.TrackingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderID = 1;</code>
   */
  java.lang.String getOrderID();
  /**
   * <code>string orderID = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();
}
