// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trackingDelivery.proto

package grpc.smartWarehouse.trackingDelivery;

public interface trackingReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.trackingReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderID = 1;</code>
   */
  java.lang.String getOrderID();
  /**
   * <code>string orderID = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIDBytes();

  /**
   * <code>string currentStatus = 2;</code>
   */
  java.lang.String getCurrentStatus();
  /**
   * <code>string currentStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getCurrentStatusBytes();

  /**
   * <code>string success_failureMessage = 3;</code>
   */
  java.lang.String getSuccessFailureMessage();
  /**
   * <code>string success_failureMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getSuccessFailureMessageBytes();
}
