// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventoryManagement.proto

package grpc.smartWarehouse.inventoryManagement;

public interface checkItemReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.checkItemReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentQuantities = 1;</code>
   */
  java.lang.String getCurrentQuantities();
  /**
   * <code>string currentQuantities = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentQuantitiesBytes();
}
