// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventoryManagement.proto

package grpc.smartWarehouse.inventoryManagement;

public interface checkItemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartwarehouse.checkItemRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string itemID = 1;</code>
   */
  java.lang.String getItemID();
  /**
   * <code>string itemID = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemIDBytes();
}
