// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventoryManagement.proto

package grpc.smartWarehouse.inventoryManagement;

/**
 * <pre>
 * Define the messages
 * </pre>
 *
 * Protobuf type {@code smartwarehouse.InventoryRequest}
 */
public  final class InventoryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartwarehouse.InventoryRequest)
    InventoryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InventoryRequest.newBuilder() to construct.
  private InventoryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InventoryRequest() {
    itemID_ = "";
    updateQuantity_ = 0;
    threshold_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InventoryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            itemID_ = s;
            break;
          }
          case 16: {

            updateQuantity_ = input.readInt32();
            break;
          }
          case 24: {

            threshold_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.smartWarehouse.inventoryManagement.InventoryManagementServiceImpl.internal_static_smartwarehouse_InventoryRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.smartWarehouse.inventoryManagement.InventoryManagementServiceImpl.internal_static_smartwarehouse_InventoryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.smartWarehouse.inventoryManagement.InventoryRequest.class, grpc.smartWarehouse.inventoryManagement.InventoryRequest.Builder.class);
  }

  public static final int ITEMID_FIELD_NUMBER = 1;
  private volatile java.lang.Object itemID_;
  /**
   * <code>string itemID = 1;</code>
   */
  public java.lang.String getItemID() {
    java.lang.Object ref = itemID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      itemID_ = s;
      return s;
    }
  }
  /**
   * <code>string itemID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getItemIDBytes() {
    java.lang.Object ref = itemID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      itemID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATEQUANTITY_FIELD_NUMBER = 2;
  private int updateQuantity_;
  /**
   * <code>int32 updateQuantity = 2;</code>
   */
  public int getUpdateQuantity() {
    return updateQuantity_;
  }

  public static final int THRESHOLD_FIELD_NUMBER = 3;
  private int threshold_;
  /**
   * <code>int32 threshold = 3;</code>
   */
  public int getThreshold() {
    return threshold_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getItemIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, itemID_);
    }
    if (updateQuantity_ != 0) {
      output.writeInt32(2, updateQuantity_);
    }
    if (threshold_ != 0) {
      output.writeInt32(3, threshold_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getItemIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, itemID_);
    }
    if (updateQuantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, updateQuantity_);
    }
    if (threshold_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, threshold_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.smartWarehouse.inventoryManagement.InventoryRequest)) {
      return super.equals(obj);
    }
    grpc.smartWarehouse.inventoryManagement.InventoryRequest other = (grpc.smartWarehouse.inventoryManagement.InventoryRequest) obj;

    boolean result = true;
    result = result && getItemID()
        .equals(other.getItemID());
    result = result && (getUpdateQuantity()
        == other.getUpdateQuantity());
    result = result && (getThreshold()
        == other.getThreshold());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ITEMID_FIELD_NUMBER;
    hash = (53 * hash) + getItemID().hashCode();
    hash = (37 * hash) + UPDATEQUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateQuantity();
    hash = (37 * hash) + THRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + getThreshold();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.smartWarehouse.inventoryManagement.InventoryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Define the messages
   * </pre>
   *
   * Protobuf type {@code smartwarehouse.InventoryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartwarehouse.InventoryRequest)
      grpc.smartWarehouse.inventoryManagement.InventoryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.smartWarehouse.inventoryManagement.InventoryManagementServiceImpl.internal_static_smartwarehouse_InventoryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.smartWarehouse.inventoryManagement.InventoryManagementServiceImpl.internal_static_smartwarehouse_InventoryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.smartWarehouse.inventoryManagement.InventoryRequest.class, grpc.smartWarehouse.inventoryManagement.InventoryRequest.Builder.class);
    }

    // Construct using grpc.smartWarehouse.inventoryManagement.InventoryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      itemID_ = "";

      updateQuantity_ = 0;

      threshold_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.smartWarehouse.inventoryManagement.InventoryManagementServiceImpl.internal_static_smartwarehouse_InventoryRequest_descriptor;
    }

    @java.lang.Override
    public grpc.smartWarehouse.inventoryManagement.InventoryRequest getDefaultInstanceForType() {
      return grpc.smartWarehouse.inventoryManagement.InventoryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.smartWarehouse.inventoryManagement.InventoryRequest build() {
      grpc.smartWarehouse.inventoryManagement.InventoryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.smartWarehouse.inventoryManagement.InventoryRequest buildPartial() {
      grpc.smartWarehouse.inventoryManagement.InventoryRequest result = new grpc.smartWarehouse.inventoryManagement.InventoryRequest(this);
      result.itemID_ = itemID_;
      result.updateQuantity_ = updateQuantity_;
      result.threshold_ = threshold_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.smartWarehouse.inventoryManagement.InventoryRequest) {
        return mergeFrom((grpc.smartWarehouse.inventoryManagement.InventoryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.smartWarehouse.inventoryManagement.InventoryRequest other) {
      if (other == grpc.smartWarehouse.inventoryManagement.InventoryRequest.getDefaultInstance()) return this;
      if (!other.getItemID().isEmpty()) {
        itemID_ = other.itemID_;
        onChanged();
      }
      if (other.getUpdateQuantity() != 0) {
        setUpdateQuantity(other.getUpdateQuantity());
      }
      if (other.getThreshold() != 0) {
        setThreshold(other.getThreshold());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.smartWarehouse.inventoryManagement.InventoryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.smartWarehouse.inventoryManagement.InventoryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object itemID_ = "";
    /**
     * <code>string itemID = 1;</code>
     */
    public java.lang.String getItemID() {
      java.lang.Object ref = itemID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string itemID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemIDBytes() {
      java.lang.Object ref = itemID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string itemID = 1;</code>
     */
    public Builder setItemID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      itemID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string itemID = 1;</code>
     */
    public Builder clearItemID() {
      
      itemID_ = getDefaultInstance().getItemID();
      onChanged();
      return this;
    }
    /**
     * <code>string itemID = 1;</code>
     */
    public Builder setItemIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      itemID_ = value;
      onChanged();
      return this;
    }

    private int updateQuantity_ ;
    /**
     * <code>int32 updateQuantity = 2;</code>
     */
    public int getUpdateQuantity() {
      return updateQuantity_;
    }
    /**
     * <code>int32 updateQuantity = 2;</code>
     */
    public Builder setUpdateQuantity(int value) {
      
      updateQuantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 updateQuantity = 2;</code>
     */
    public Builder clearUpdateQuantity() {
      
      updateQuantity_ = 0;
      onChanged();
      return this;
    }

    private int threshold_ ;
    /**
     * <code>int32 threshold = 3;</code>
     */
    public int getThreshold() {
      return threshold_;
    }
    /**
     * <code>int32 threshold = 3;</code>
     */
    public Builder setThreshold(int value) {
      
      threshold_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 threshold = 3;</code>
     */
    public Builder clearThreshold() {
      
      threshold_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartwarehouse.InventoryRequest)
  }

  // @@protoc_insertion_point(class_scope:smartwarehouse.InventoryRequest)
  private static final grpc.smartWarehouse.inventoryManagement.InventoryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.smartWarehouse.inventoryManagement.InventoryRequest();
  }

  public static grpc.smartWarehouse.inventoryManagement.InventoryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InventoryRequest>
      PARSER = new com.google.protobuf.AbstractParser<InventoryRequest>() {
    @java.lang.Override
    public InventoryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InventoryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InventoryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InventoryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.smartWarehouse.inventoryManagement.InventoryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

