// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventoryManagement.proto

package grpc.smartWarehouse.inventoryManagement;

public final class InventoryManagementServiceImpl {
  private InventoryManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_CheckItemRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_CheckItemRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_CheckItemReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_CheckItemReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031inventoryManagement.proto\022\016smartwareho" +
      "use\"\"\n\020CheckItemRequest\022\016\n\006itemID\030\001 \001(\t\"" +
      "+\n\016CheckItemReply\022\031\n\021currentQuantities\030\001" +
      " \001(\t2f\n\023InventoryManagement\022O\n\tcheckItem" +
      "\022 .smartwarehouse.CheckItemRequest\032\036.sma" +
      "rtwarehouse.CheckItemReply\"\000BK\n\'grpc.sma" +
      "rtWarehouse.inventoryManagementB\036Invento" +
      "ryManagementServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartwarehouse_CheckItemRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartwarehouse_CheckItemRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_CheckItemRequest_descriptor,
        new java.lang.String[] { "ItemID", });
    internal_static_smartwarehouse_CheckItemReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartwarehouse_CheckItemReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_CheckItemReply_descriptor,
        new java.lang.String[] { "CurrentQuantities", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
