// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orderManagement.proto

package grpc.smartWarehouse.orderManagement;

public final class OrderManagementServiceImpl {
  private OrderManagementServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_orderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_orderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartwarehouse_orderReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartwarehouse_orderReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025orderManagement.proto\022\016smartwarehouse\"" +
      "O\n\014orderRequest\022\024\n\014customerName\030\001 \001(\t\022\016\n" +
      "\006itemID\030\002 \001(\t\022\031\n\021currentQuantities\030\003 \001(\t" +
      "\"T\n\norderReply\022\017\n\007orderID\030\001 \001(\t\022\025\n\rcurre" +
      "ntStatus\030\002 \001(\t\022\036\n\026success_failureMessage" +
      "\030\003 \001(\t2Z\n\017OrderManagement\022G\n\torderItem\022\034" +
      ".smartwarehouse.orderRequest\032\032.smartware" +
      "house.orderReply\"\000BC\n#grpc.smartWarehous" +
      "e.orderManagementB\032OrderManagementServic" +
      "eImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartwarehouse_orderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartwarehouse_orderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_orderRequest_descriptor,
        new java.lang.String[] { "CustomerName", "ItemID", "CurrentQuantities", });
    internal_static_smartwarehouse_orderReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartwarehouse_orderReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartwarehouse_orderReply_descriptor,
        new java.lang.String[] { "OrderID", "CurrentStatus", "SuccessFailureMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
